name: instagram
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.5
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.15.2
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.5
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.4
  ionicons: ^0.2.2
  rename: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ic_instagram.svg
    - assets/images/defaultProfilePicture.jpg
    - assets/images/ic_reel.svg
    - assets/images/ic_reel_outlined.svg
